from __future__ import annotations

from typing import Any, Mapping, Protocol


class ResearchToolGateway(Protocol):
    """Domain allowlist shared by external agents, API and future MCP adapters.

    No arbitrary shell, arbitrary path, credential or live-trading operation belongs
    on this interface.
    """

    def intake_strategy(self, payload: Mapping[str, Any]) -> Mapping[str, Any]: ...

    def formalize_strategy(self, draft_id: str) -> Mapping[str, Any]: ...

    def list_ambiguities(self, draft_id: str) -> list[Mapping[str, Any]]: ...

    def freeze_baseline(self, draft_id: str, approval_id: str) -> Mapping[str, Any]: ...

    def create_experiment_plan(self, payload: Mapping[str, Any]) -> Mapping[str, Any]: ...

    def approve_experiment_plan(self, plan_id: str) -> Mapping[str, Any]: ...

    def run_backtest(self, plan_id: str) -> Mapping[str, Any]: ...

    def run_parameter_search(self, plan_id: str) -> Mapping[str, Any]: ...

    def get_job(self, job_id: str) -> Mapping[str, Any]: ...

    def get_agent_run(self, agent_run_id: str) -> Mapping[str, Any]: ...

    def compare_runs(self, run_ids: list[str]) -> Mapping[str, Any]: ...

    def propose_strategy_version(self, payload: Mapping[str, Any]) -> Mapping[str, Any]: ...

    def accept_proposal(self, proposal_id: str) -> Mapping[str, Any]: ...

    def reject_proposal(self, proposal_id: str) -> Mapping[str, Any]: ...

    def generate_report(self, job_id: str) -> Mapping[str, Any]: ...
