from __future__ import annotations

from typing import Any, Mapping, Protocol, Sequence

from .models import AuditEvent, Job, Message, ResearchSession, StrategyDraft, StrategyVersion


class ProductRepository(Protocol):
    """Persistence port for local product state."""

    def initialize(self) -> None: ...

    def create_session(self, session: ResearchSession) -> ResearchSession: ...

    def list_sessions(self) -> Sequence[ResearchSession]: ...

    def get_session(self, session_id: str) -> ResearchSession: ...

    def add_message(self, message: Message) -> Message: ...

    def list_messages(self, session_id: str) -> Sequence[Message]: ...

    def create_draft(self, draft: StrategyDraft) -> StrategyDraft: ...

    def list_drafts(self, session_id: str | None = None) -> Sequence[StrategyDraft]: ...

    def get_draft(self, draft_id: str) -> StrategyDraft: ...

    def freeze_baseline(
        self,
        *,
        draft_id: str,
        version_id: str,
        approval_id: str,
        created_at: str,
    ) -> StrategyVersion: ...

    def create_job(self, job: Job) -> Job: ...

    def list_jobs(self) -> Sequence[Job]: ...

    def get_job(self, job_id: str) -> Job: ...

    def list_job_logs(self, job_id: str) -> Sequence[Mapping[str, Any]]: ...

    def append_event(self, event: AuditEvent) -> AuditEvent: ...

    def list_events(self, *, limit: int = 100) -> Sequence[AuditEvent]: ...
