from __future__ import annotations

from typing import Any, Mapping, Protocol, Sequence

from .models import (
    AgentRun,
    Artifact,
    AuditEvent,
    ExperimentPlan,
    Job,
    Message,
    ResearchSession,
    StrategyDraft,
    StrategyVersion,
    ToolCall,
    Trial,
)


class ProductRepository(Protocol):
    """Persistence port for local product state."""

    def initialize(self) -> None: ...

    def create_session(self, session: ResearchSession) -> ResearchSession: ...

    def list_sessions(self) -> Sequence[ResearchSession]: ...

    def get_session(self, session_id: str) -> ResearchSession: ...

    def add_message(self, message: Message) -> Message: ...

    def list_messages(self, session_id: str) -> Sequence[Message]: ...

    def create_draft(self, draft: StrategyDraft) -> StrategyDraft: ...

    def list_drafts(self, session_id: str | None = None) -> Sequence[StrategyDraft]: ...

    def get_draft(self, draft_id: str) -> StrategyDraft: ...

    def freeze_baseline(
        self,
        *,
        draft_id: str,
        version_id: str,
        approval_id: str,
        created_at: str,
    ) -> StrategyVersion: ...

    def create_job(self, job: Job) -> Job: ...

    def list_jobs(self) -> Sequence[Job]: ...

    def get_job(self, job_id: str) -> Job: ...

    def list_job_logs(self, job_id: str) -> Sequence[Mapping[str, Any]]: ...

    def append_event(self, event: AuditEvent) -> AuditEvent: ...

    def list_events(self, *, limit: int = 100) -> Sequence[AuditEvent]: ...

    def create_experiment_plan(self, plan: ExperimentPlan) -> ExperimentPlan: ...

    def get_experiment_plan(self, plan_id: str) -> ExperimentPlan: ...

    def list_experiment_plans(self) -> Sequence[ExperimentPlan]: ...

    def approve_experiment_plan(
        self,
        plan: ExperimentPlan,
        *,
        approval_id: str,
        created_at: str,
    ) -> ExperimentPlan: ...

    def create_trial(self, trial: Trial) -> Trial: ...

    def list_trials(self, plan_id: str) -> Sequence[Trial]: ...

    def create_agent_run(self, agent_run: AgentRun) -> AgentRun: ...

    def get_agent_run(self, agent_run_id: str) -> AgentRun: ...

    def list_agent_runs(self) -> Sequence[AgentRun]: ...

    def create_tool_call(self, tool_call: ToolCall) -> ToolCall: ...

    def list_tool_calls(self, agent_run_id: str) -> Sequence[ToolCall]: ...

    def create_artifact(self, artifact: Artifact) -> Artifact: ...

    def list_artifacts(self, agent_run_id: str) -> Sequence[Artifact]: ...
